version: "3"

networks:
  lambada-coprocessor-network:
    name: lambada-coprocessor-network
    driver: bridge

services:

  anvil:
    image: ghcr.io/foundry-rs/foundry
    container_name: anvil
    ports:
      - 8545:8545
    entrypoint: anvil
    volumes:
      - ./docker-compose/anvil-state.json:/root/.anvil/state.json
    command: --host 0.0.0.0 --load-state /root/.anvil/state.json
    networks:
      - lambada-coprocessor-network

  aggregator:
    build:
      context: .
      dockerfile: aggregator.Dockerfile
    container_name: lambada-coprocessor-aggregator
    ports:
      - 8080:8080
    depends_on:
      anvil:
        condition: service_started
    volumes:
      - ./:/lambada-coprocessor/
    working_dir: /lambada-coprocessor
    command: 
      - --config 
      - config-files/aggregator-docker-compose.yaml
      - --credible-squaring-deployment 
      - contracts/script/output/31337/credible_squaring_avs_deployment_output.json
      - --ecdsa-private-key 
      - "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6"
    networks:
      - lambada-coprocessor-network

  machine1:
    image: zippiehq/cartesi-lambada:1.0
    container_name: lambada-coprocessor-machine1
    volumes:
      - ./docker-compose/operators/data/operator1:/data
      - ./machine/data-preload:/data/preload
    networks:
      - lambada-coprocessor-network
    environment:
      - COMPUTE_ONLY=1

  operator1:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: lambada-coprocessor-operator1
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      machine1:
        condition: service_started
    environment:
      - IPFS_ADDRESS=machine1:5001
      - LAMBADA_ADDRESS=machine1:3033
      - LAMBADA_COMPUTE_CID=bafybeicyzbzllftccnty6mb66au3zyyb4646cnvdyozrfym3yjlerbs5iu
      - OPERATOR_BLS_KEY_PASSWORD=2MNS8S9ZTwmvmtSDtqeS
      - OPERATOR_ECDSA_KEY_PASSWORD=FbyHuSJL31m8F6GQltsT
    volumes:
      - ./:/lambada-coprocessor/
    working_dir: /lambada-coprocessor
    command: --config docker-compose/operators/configs/operator1.yaml
    networks:
      - lambada-coprocessor-network

  machine2:
    image: zippiehq/cartesi-lambada:1.0
    container_name: lambada-coprocessor-machine2
    volumes:
      - ./docker-compose/operators/data/operator2:/data
      - ./machine/data-preload:/data/preload
    networks:
      - lambada-coprocessor-network
    environment:
      - COMPUTE_ONLY=1

  operator2:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: lambada-coprocessor-operator2
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      machine1:
        condition: service_started
    environment:
      - IPFS_ADDRESS=machine2:5001
      - LAMBADA_ADDRESS=machine2:3033
      - LAMBADA_COMPUTE_CID=bafybeicyzbzllftccnty6mb66au3zyyb4646cnvdyozrfym3yjlerbs5iu
      - OPERATOR_BLS_KEY_PASSWORD=13ABrhIAy77DRP1I8M6T
      - OPERATOR_ECDSA_KEY_PASSWORD=2VTgW9qlwEbbBdqX0YxR
    volumes:
      - ./:/lambada-coprocessor/
    working_dir: /lambada-coprocessor
    command: --config docker-compose/operators/configs/operator2.yaml
    networks:
      - lambada-coprocessor-network

  machine3:
    image: zippiehq/cartesi-lambada:1.0
    container_name: lambada-coprocessor-machine3
    volumes:
      - ./docker-compose/operators/data/operator3:/data
      - ./machine/data-preload:/data/preload
    networks:
      - lambada-coprocessor-network
    environment:
      - COMPUTE_ONLY=1

  operator3:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: lambada-coprocessor-operator3
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      machine1:
        condition: service_started
    environment:
      - IPFS_ADDRESS=machine3:5001
      - LAMBADA_ADDRESS=machine3:3033
      - LAMBADA_COMPUTE_CID=bafybeicyzbzllftccnty6mb66au3zyyb4646cnvdyozrfym3yjlerbs5iu
      - OPERATOR_BLS_KEY_PASSWORD=hFxK1mexwuC3ezlk9Hmy
      - OPERATOR_ECDSA_KEY_PASSWORD=1IiT09BboEqcfCNvbFpn
    volumes:
      - ./:/lambada-coprocessor/
    working_dir: /lambada-coprocessor
    command: --config docker-compose/operators/configs/operator3.yaml
    networks:
      - lambada-coprocessor-network
