version: "3"

networks:
  lambada-coprocessor-network:
    name: lambada-coprocessor-network
    driver: bridge

services:

  anvil:
    image: ghcr.io/foundry-rs/foundry
    container_name: anvil
    ports:
      - 8545:8545
    entrypoint: anvil
    volumes:
      - ./tests/anvil/avs-and-eigenlayer-deployed-anvil-state.json:/root/.anvil/state.json
    command: --host 0.0.0.0 --load-state /root/.anvil/state.json
    networks:
      - lambada-coprocessor-network

  aggregator:
    build:
      context: .
      dockerfile: aggregator.Dockerfile
    container_name: lambada-coprocessor-aggregator
    ports:
      - 8080:8080
    depends_on:
      anvil:
        condition: service_started
    volumes:
      - ./:/lambada-coprocessor/
    working_dir: /lambada-coprocessor
    command: 
      - --config 
      - tests/nodes/aggregator/aggregator-docker-compose.yaml
      - --credible-squaring-deployment 
      - contracts/script/output/31337/lambada_coprocessor_avs_deployment_output.json
      - --ecdsa-private-key 
      - "0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6"
    networks:
      - lambada-coprocessor-network

  machine1:
    image: ghcr.io/zippiehq/cartesi-lambada:amd64-latest
    container_name: lambada-coprocessor-machine1
    volumes:
      - ./tests/nodes/operators/data/operator1:/data
      - ./machine/data-preload:/data/preload
    networks:
      - lambada-coprocessor-network
    environment:
      - COMPUTE_ONLY=1

  operator1:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: lambada-coprocessor-operator1
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      machine1:
        condition: service_started
    environment:
      - IPFS_ADDRESS=machine1:5001
      - LAMBADA_ADDRESS=machine1:3033
      - LAMBADA_COMPUTE_CID=bafybeicdhhtwmgpnt7jugvlv3xtp2u4w4mkunpmg6txkkkjhpvnt2buyqa
      - OPERATOR_BLS_KEY_PASSWORD=yk2DOST1Ifr2SEmNVc9F
      - OPERATOR_ECDSA_KEY_PASSWORD=H8d17sFpRHZ1EXXfdyeO
    volumes:
      - ./:/lambada-coprocessor/
    working_dir: /lambada-coprocessor
    command: --config tests/nodes/operators/configs/operator1.yaml
    networks:
      - lambada-coprocessor-network

  machine2:
    image: ghcr.io/zippiehq/cartesi-lambada:amd64-latest
    container_name: lambada-coprocessor-machine2
    volumes:
      - ./tests/nodes/operators/data/operator2:/data
      - ./machine/data-preload:/data/preload
    networks:
      - lambada-coprocessor-network
    environment:
      - COMPUTE_ONLY=1

  operator2:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: lambada-coprocessor-operator2
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      machine1:
        condition: service_started
    environment:
      - IPFS_ADDRESS=machine2:5001
      - LAMBADA_ADDRESS=machine2:3033
      - LAMBADA_COMPUTE_CID=bafybeicdhhtwmgpnt7jugvlv3xtp2u4w4mkunpmg6txkkkjhpvnt2buyqa
      - OPERATOR_BLS_KEY_PASSWORD=qJf4pUCKRRgfWfEHx6EK
      - OPERATOR_ECDSA_KEY_PASSWORD=cLuEf1Yho9pKKQnGIa7D
    volumes:
      - ./:/lambada-coprocessor/
    working_dir: /lambada-coprocessor
    command: --config tests/nodes/operators/configs/operator2.yaml
    networks:
      - lambada-coprocessor-network

  machine3:
    image: ghcr.io/zippiehq/cartesi-lambada:amd64-latest
    container_name: lambada-coprocessor-machine3
    volumes:
      - ./tests/nodes/operators/data/operator3:/data
      - ./machine/data-preload:/data/preload
    networks:
      - lambada-coprocessor-network
    environment:
      - COMPUTE_ONLY=1

  operator3:
    build:
      context: .
      dockerfile: operator.Dockerfile
    container_name: lambada-coprocessor-operator3
    depends_on:
      anvil:
        condition: service_started
      aggregator:
        condition: service_started
      machine1:
        condition: service_started
    environment:
      - IPFS_ADDRESS=machine3:5001
      - LAMBADA_ADDRESS=machine3:3033
      - LAMBADA_COMPUTE_CID=bafybeicdhhtwmgpnt7jugvlv3xtp2u4w4mkunpmg6txkkkjhpvnt2buyqa
      - OPERATOR_BLS_KEY_PASSWORD=2f74aPUitNNYJA7SGBnK
      - OPERATOR_ECDSA_KEY_PASSWORD=UcYIuU73ILRbP6vwfJQp
    volumes:
      - ./:/lambada-coprocessor/
    working_dir: /lambada-coprocessor
    command: --config tests/nodes/operators/configs/operator3.yaml
    networks:
      - lambada-coprocessor-network
