production: true

operator_address: 0x0f051c17eaa40511ddf80f826ee56a0222d3ad8a

avs_registry_coordinator_address: 0xc3e53F4d16Ae77Db1c982e75a937B9f60FE63690
operator_state_retriever_address: 0x1613beB3B2C4f22Ee086B2b38C1476A3cE7f78E8

eth_rpc_url: http://anvil:8545
eth_ws_url: ws://anvil:8545

ecdsa_private_key_store_path: docker-compose/operators/keys/ecdsa-5b310bde-cef0-11ee-b601-a036bcd1ceee/keys/2.ecdsa.key.json
bls_private_key_store_path: docker-compose/operators/keys/bls-5c228993-cef0-11ee-b601-a036bcd1ceee/keys/2.bls.key.json

aggregator_server_ip_port_address: lambada-coprocessor-aggregator:8090

enable_metrics: true
eigen_metrics_ip_port_address: 0.0.0.0:9090

enable_node_api: true
node_api_ip_port_address: 0.0.0.0:9010

register_operator_on_startup: true
token_strategy_addr: 0xa85233C63b9Ee964Add6F2cffe00Fd84eb32338f
